import {
  Home,
  Settings,
  FileText,
  Shield,
  Building2,
  BookOpen,
  FileCheck2,
  LogOut,
  Menu,
  Check,
  AlertTriangle,
  Target,
  Loader2,
  CircleCheck,
  ClipboardCheck,
  Download,
  Timer,
  ChevronLeft,
  TrendingUp,
  CloudDownload,
  type Icon as LucideIcon,
} from 'lucide-react'

export type Icon = LucideIcon

export const Icons = {
  logo: Shield,
  home: Home,
  settings: Settings,
  file: FileText,
  fileText: FileText,
  shield: Shield,
  building: Building2,
  book: BookOpen,
  check: Check,
  checkCircle: CircleCheck,
  fileCheck: FileCheck2,
  logout: LogOut,
  menu: Menu,
  warning: AlertTriangle,
  target: Target,
  spinner: Loader2,
  clipboard: ClipboardCheck,
  download: Download,
  cloudDownload: CloudDownload,
  timer: Timer,
  chevronLeft: ChevronLeft,
  trendingUp: TrendingUp,
}
